### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by triplem** [sf666/nextcp2#1]
I switched to jdk8 and ran build_dependencies.sh, but this is throwing errors. Building lemma reports, that seamless-javadoc cannot be found. 
I already tried to build seamless before lemma, but the error still occurs. Changing the required version of seamless in the lemma-pom seems to fix this problem, Now the lemma build fails with an error in a test.
To make it easier to re-produce the build of this nice-looking control point, I suggest, that the dependencies are published to a github maven repository (see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry).

**Comment by sf666** [comment]
Hi, I'll try to reproduce the build error ...

**Comment by sf666** [comment]
Thank's for trying nextcp/2. Most likely I'll need some external feedback for getting the UI "smooth".

I believe, even though you have installed JDK 8,  your maven installation uses a JDK > 8. Please check your JAVA_HOME environment variable. It sould point tot a JDK 8 release.

Using SDKMAN (as described in readme.md) should fix it (don't use user root).

Too bad, that lemma und cling are not under active development any more. 

mvn -DskipTests=true install

**Comment by triplem** [comment]
Hm, my JDK8 is installed and "active". I have then already skipped the tests 👍 
Will try it once more and report back. 
Still I guess, that the sequence (first lemma, then seamless) is not the intended order, is it?

**Comment by sf666** [comment]
I have created a public repo, so the build should now be easier to reproduce.
